#!/usr/bin/env python3
"""Render Tarrawarra's gridded HLI covariate for diagnosis.

This plots the actual gridded terrain-covariate layer generated by the
DownscalingMoistureModel terrain pipeline for the Tarrawarra validation bbox,
not an interpolation of point-sampled HLI values.
"""

from __future__ import annotations

import argparse
import json
import os
import sys
from datetime import date
from pathlib import Path
from shutil import copy2

os.environ.setdefault("NUMBA_DISABLE_JIT", "1")

import matplotlib

matplotlib.use("Agg")

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd


ROOT = Path(__file__).resolve().parents[3]
LOCAL_PADDOCKTS_ROOT = ROOT / "outputs/paddockts_local"
os.environ.setdefault("PADDOCKTS_OUTDIR", str(LOCAL_PADDOCKTS_ROOT / "outputs"))
os.environ.setdefault("PADDOCKTS_TMPDIR", str(LOCAL_PADDOCKTS_ROOT / "tmp"))
os.environ.setdefault("PADDOCKTS_CONFIG", str(LOCAL_PADDOCKTS_ROOT / "PaddockTS.local.json"))
DEFAULT_DMM_REPO = Path("/Volumes/Dmitry_work/borevitz_projects/DownscalingMoistureModel")
DEFAULT_BBOX = ROOT / "outputs/tarrawarra_conversion/tarrawarra_points_bbox.json"
DEFAULT_TABLE = ROOT / "outputs/tarrawarra_model6_vs_model8/model6_model8_combined_predictions_valid_30m_gridcell.csv"
DEFAULT_OUTDIR = ROOT / "outputs/tarrawarra_model6_vs_model8/ancillary"
DEFAULT_FIG = (
    ROOT
    / "reports/analyses/unified_dense_validation/figures/terrain_covariates/"
    / "tarrawarra_hli_30m_model_terrain_grid.png"
)


def _tag(*parts: object) -> str:
    return "_".join(str(p) for p in parts).replace(".", "p").replace("-", "m").replace("/", "_")


def read_bbox(path: Path) -> tuple[float, float, float, float]:
    payload = json.loads(path.read_text(encoding="utf-8"))
    return (float(payload["west"]), float(payload["south"]), float(payload["east"]), float(payload["north"]))


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--dmm-repo", type=Path, default=DEFAULT_DMM_REPO)
    parser.add_argument("--bbox-json", type=Path, default=DEFAULT_BBOX)
    parser.add_argument("--validation-table", type=Path, default=DEFAULT_TABLE)
    parser.add_argument("--outdir", type=Path, default=DEFAULT_OUTDIR)
    parser.add_argument("--figure", type=Path, default=DEFAULT_FIG)
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    args.outdir.mkdir(parents=True, exist_ok=True)
    args.figure.parent.mkdir(parents=True, exist_ok=True)

    if str(args.dmm_repo) not in sys.path:
        sys.path.insert(0, str(args.dmm_repo))

    from PaddockTS.query import Query
    from emt.covariates import terrain_covariates

    bbox = read_bbox(args.bbox_json)
    table = pd.read_csv(args.validation_table, low_memory=False)
    table["date"] = pd.to_datetime(table["date"], errors="coerce")
    min_day = table["date"].min().date()
    max_day = table["date"].max().date()

    q = Query(
        bbox=list(bbox),
        start=min_day,
        end=max_day,
        stub=_tag("tarrawarra_features", *[f"{v:.4f}" for v in bbox], min_day, max_day),
    )
    terrain_path = Path(q.terrain_path)
    if not terrain_path.exists():
        original_cache = Path("/Users/dmitrygrishin/Downloads/PaddockTSTmp/aoi") / q.bbox_hash / "terrain.tif"
        if original_cache.exists():
            terrain_path.parent.mkdir(parents=True, exist_ok=True)
            copy2(original_cache, terrain_path)
            success = original_cache.with_name(original_cache.name + "._SUCCESS")
            if success.exists():
                copy2(success, terrain_path.with_name(terrain_path.name + "._SUCCESS"))
            else:
                terrain_path.with_name(terrain_path.name + "._SUCCESS").write_text("copied from cache\n", encoding="utf-8")
    elif not terrain_path.with_name(terrain_path.name + "._SUCCESS").exists():
        terrain_path.with_name(terrain_path.name + "._SUCCESS").write_text("existing local cache\n", encoding="utf-8")
    terrain = terrain_covariates(q)
    hli = terrain["hli"]

    hli_tif = args.outdir / "tarrawarra_hli_30m_model_terrain_grid.tif"
    hli.rio.to_raster(hli_tif)

    supports = (
        table.drop_duplicates("point_id")
        .dropna(subset=["grid_x", "grid_y", "hli"])
        [["point_id", "grid_x", "grid_y", "hli"]]
    )

    arr = hli.values.astype(float)
    finite = arr[np.isfinite(arr)]
    x = np.asarray(hli["x"].values, dtype=float)
    y = np.asarray(hli["y"].values, dtype=float)
    extent = (float(np.nanmin(x)), float(np.nanmax(x)), float(np.nanmin(y)), float(np.nanmax(y)))
    origin = "upper" if y[0] > y[-1] else "lower"
    vmin, vmax = np.nanpercentile(finite, [2, 98])

    fig, axes = plt.subplots(1, 2, figsize=(12.5, 5.6), gridspec_kw={"width_ratios": [1.35, 0.8]})
    ax = axes[0]
    im = ax.imshow(arr, extent=extent, origin=origin, cmap="inferno", vmin=vmin, vmax=vmax)
    ax.scatter(
        supports["grid_x"],
        supports["grid_y"],
        c=supports["hli"],
        cmap="inferno",
        vmin=vmin,
        vmax=vmax,
        s=18,
        edgecolor="white",
        linewidth=0.25,
        alpha=0.9,
    )
    ax.set_aspect("equal")
    ax.set_title("Tarrawarra HLI covariate grid")
    ax.set_xlabel(f"x ({terrain.rio.crs})")
    ax.set_ylabel(f"y ({terrain.rio.crs})")
    cbar = fig.colorbar(im, ax=ax, shrink=0.86)
    cbar.set_label("HLI")

    axh = axes[1]
    axh.hist(finite, bins=24, color="0.80", edgecolor="white", label="all grid cells")
    axh.axvline(np.nanmedian(finite), color="0.25", linewidth=1.5, label=f"grid median {np.nanmedian(finite):.3f}")
    axh.axvline(supports["hli"].median(), color="#CC6677", linewidth=1.8, label=f"support median {supports['hli'].median():.3f}")
    axh.scatter(
        supports["hli"],
        np.full(len(supports), -0.8),
        s=14,
        color="#CC6677",
        alpha=0.55,
        edgecolor="none",
        label="validation supports",
    )
    axh.set_ylim(bottom=-2)
    axh.set_xlabel("HLI")
    axh.set_ylabel("grid-cell count")
    axh.set_title("Raster/support HLI distribution")
    axh.legend(frameon=False, fontsize=8)

    fig.suptitle(
        "Tarrawarra heat-load index (HLI): gridded model terrain covariate with 30 m validation supports",
        y=1.02,
    )
    fig.tight_layout()
    fig.savefig(args.figure, dpi=220, bbox_inches="tight")
    plt.close(fig)

    stats = {
        "hli_tif": str(hli_tif),
        "figure": str(args.figure),
        "crs": str(terrain.rio.crs),
        "shape_yx": list(arr.shape),
        "grid_hli_min": float(np.nanmin(finite)),
        "grid_hli_median": float(np.nanmedian(finite)),
        "grid_hli_max": float(np.nanmax(finite)),
        "support_count": int(len(supports)),
        "support_hli_min": float(supports["hli"].min()),
        "support_hli_median": float(supports["hli"].median()),
        "support_hli_max": float(supports["hli"].max()),
    }
    stats_path = args.outdir / "tarrawarra_hli_30m_model_terrain_grid_summary.json"
    stats_path.write_text(json.dumps(stats, indent=2), encoding="utf-8")
    print(json.dumps(stats, indent=2))


if __name__ == "__main__":
    main()
